# -*- coding: utf-8 -*-
"""Remoção de Duplicatas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QEHgLS4O8ju5euHYxoS16l3ZVrIwaoe9
"""

import pandas as pd

arquivo = 'dataset-duat-duplicado.csv'

# Lê o arquivo CSV
df = pd.read_csv(arquivo)

# Printa as linhas com a verificação de duplicadas
print(df.duplicated())

# Se tiver duplicata Lê
if df.duplicated().any():
  print(f"Existem {df.duplicated().sum()} linhas duplicadas no arquivo.\n")

  # Remove as duplicatas completas
  df_limpo = df.drop_duplicates()

  print(f"Total de linhas antes: {len(df)}")
  print(f"Total de linhas depois: {len(df_limpo)}")

  # Salva o resultado em um novo arquivo CSV
  df_limpo.to_csv('dataset-duat-sem-duplicadas.csv', index=False)
  print("\nNovo arquivo 'dataset-duat-sem-duplicadas.csv' gerado com sucesso!")
else:
  print("\nNão existem linhas duplicadas no arquivo.")

"""
import pandas as pd

arquivo = 'dataset-duat.csv'
df = pd.read_csv(arquivo)

# Duplica todas as linhas empilhando o DataFrame com ele mesmo
df_duplicado = pd.concat([df, df], ignore_index=True)

# Salva o resultado em um novo CSV
df_duplicado.to_csv('dataset-duat-duplicado.csv', index=False)

print(f"Linhas originais: {len(df)}")
print(f"Linhas após duplicar: {len(df_duplicado)}")
"""